/**
 * Simple name-based gender detection.
 * Returns 'male', 'female', or null if undetermined.
 */

const MALE_NAMES = new Set([
  'aaron','abdul','abdullah','abraham','adam','adrian','ahmad','ahmed','aidan','aiden',
  'alan','albert','alejandro','alex','alexander','alfred','ali','allen','alvin','amir',
  'amos','anderson','andre','andrew','andy','angel','anthony','antonio','archer','ari',
  'arjun','armand','arnold','arthur','aryan','asher','ashton','august','austin',
  'barry','beau','ben','benjamin','bennett','bernard','bill','billy','blake','bobby',
  'brad','bradley','brandon','brayden','brendan','brett','brian','bruce','bruno','bryan',
  'bryce','byron',
  'caleb','calvin','cameron','carl','carlos','carter','casey','cedric','chad','charles',
  'charlie','chase','chris','christian','christopher','clarence','clark','clay','clayton',
  'clifford','clint','clinton','clyde','cody','cole','colin','colton','connor','conrad',
  'corey','craig','curtis','cyrus',
  'dale','damian','damon','dan','daniel','danny','dante','darius','darren','darwin',
  'dave','david','dean','dennis','derek','desmond','devin','dimitri','dirk','dominic',
  'don','donald','douglas','drew','duke','duncan','dustin','dwight','dylan',
  'earl','eddie','edgar','edmund','edward','edwin','eli','elias','elijah','elliott',
  'ellis','emanuel','emilio','emmanuel','emmett','eric','erik','ernest','ernie','ethan',
  'eugene','evan','everett','ezra',
  'fabian','felipe','felix','fernando','finn','fletcher','floyd','ford','francis',
  'francisco','frank','franklin','fred','frederick',
  'gabriel','garrett','gary','gavin','gene','george','gerald','gilbert','giovanni',
  'glen','glenn','gordon','grace','graham','grant','greg','gregory','griffin','gunnar',
  'gustavo','guy',
  'hank','harold','harris','harrison','harry','harvey','hassan','hayden','heath',
  'hector','henry','herbert','herman','homer','howard','hudson','hugh','hugo','hunter',
  'ian','ibrahim','igor','imran','irvin','irving','isaac','isaiah','ismael','ivan',
  'jack','jackson','jacob','jaden','jake','jamal','james','jamie','jared','jarvis',
  'jason','jasper','javier','jay','jayden','jeff','jefferson','jeffrey','jeremy','jerome',
  'jerry','jesse','jim','jimmy','joaquin','joe','joel','john','johnny','jon','jonah',
  'jonathan','jordan','jorge','jose','joseph','josh','joshua','juan','julian','julius',
  'justin',
  'kai','kaleb','kane','karl','keegan','keith','kelly','ken','kenneth','kent','kevin',
  'khalid','kieran','kirk','kobe','kurt','kyle',
  'lance','landon','larry','lars','lawrence','lee','leo','leon','leonard','leonardo',
  'leroy','levi','lewis','liam','lincoln','lloyd','logan','lorenzo','louis','luca',
  'lucas','luis','luke','luther',
  'mack','malcolm','malik','manuel','marc','marco','marcus','mario','mark','marshall',
  'martin','marvin','mason','mathew','matt','matthew','maurice','max','maxwell',
  'michael','miguel','mike','miles','mitchell','mohammad','mohammed','morgan','morris',
  'moses','muhammad','murray','mustafa',
  'nash','nathan','nathaniel','neil','nelson','nicholas','nick','nicolas','nigel','noah',
  'noel','nolan','norman',
  'oliver','omar','orlando','oscar','otto','owen',
  'pablo','parker','patrick','paul','pedro','perry','peter','philip','phillip','pierce',
  'porter','prakash','prashant','prince','princeton',
  'quinn',
  'rafael','rahul','raj','rajesh','ralph','ramesh','ramon','randall','randy','rashid',
  'raul','ray','raymond','reed','reginald','rene','rex','ricardo','richard','rick',
  'riley','robert','robin','rocco','rodney','rodrigo','roger','roland','roman','ronald',
  'rory','ross','roy','ruben','rudy','russell','ryan','ryder',
  'salvador','sam','samuel','santiago','santos','saul','scott','sean','sebastian',
  'sergio','seth','shane','shaun','shawn','sheldon','sid','sidney','simon','silas',
  'solomon','spencer','stanley','stefan','stephen','sterling','steve','steven','stuart',
  'sunil','sven',
  'taylor','ted','teodoro','terrence','terry','theodore','thomas','tim','timothy','tobias',
  'toby','todd','tom','tommy','tony','travis','trent','trevor','tristan','troy','tucker',
  'tyler',
  'ulysses',
  'vance','vernon','victor','vincent','virgil','vivek',
  'wade','walker','wallace','walter','warren','wayne','wesley','weston','william','willis',
  'wilson','winston','wyatt',
  'xavier','xander',
  'yusuf',
  'zachary','zane','zeke',
]);

const FEMALE_NAMES = new Set([
  'aaliyah','abigail','ada','addison','adelaide','adeline','adriana','adrienne','agatha',
  'agnes','aileen','aimee','aisha','alaina','alana','alejandra','alexa','alexandra',
  'alexis','alice','alicia','alina','alison','allison','alma','alyssa','amanda','amber',
  'amelia','amina','amy','ana','anastasia','andrea','angela','angelica','angelina',
  'angie','anita','ann','anna','annabelle','anne','annette','annie','april','ariana',
  'ariel','arlene','ashley','athena','aubrey','audrey','aurora','autumn','ava','avery',
  'barbara','beatrice','becky','belinda','bella','bernadette','bernice','bertha','bessie',
  'beth','bethany','betty','beverly','bianca','bonnie','brandy','brenda','briana',
  'bridget','brittany','brittney','brooke','brooklyn',
  'caitlin','camila','camille','candace','cara','carina','carla','carmen','carol',
  'carolina','caroline','carolyn','carrie','cassandra','cassidy','catherine','cathy',
  'cecilia','celeste','celia','chandra','charity','charlene','charlotte','chelsea',
  'cheryl','chloe','christina','christine','cindy','claire','clara','claudia',
  'colleen','constance','cora','corinne','courtney','crystal','cynthia',
  'daisy','dana','daniela','danielle','daphne','darlene','dawn','deanna','debbie',
  'deborah','debra','deirdre','delia','delilah','denise','desiree','destiny','diana',
  'diane','dina','dolores','donna','dora','doris','dorothy',
  'edith','eileen','elaine','eleanor','elena','elise','elizabeth','ella','ellen','ellie',
  'eloise','elsa','elsie','elvira','emilia','emily','emma','erica','erika','erin',
  'esmeralda','estelle','esther','ethel','eva','evangeline','eve','evelyn',
  'faith','fatima','faye','felicia','fiona','flora','florence','frances','francesca',
  'frida','frieda',
  'gabriela','gabrielle','gail','gemma','genevieve','georgia','geraldine','gillian',
  'gina','giselle','gladys','glenda','gloria','grace','greta','gretchen','guadalupe',
  'gwen','gwendolyn',
  'hadley','hailey','hannah','harmony','harper','harriet','hazel','heather','heidi',
  'helen','helena','henrietta','hillary','holly','hope',
  'ida','imani','imelda','imogen','ina','india','ingrid','irene','iris','irma','isabel',
  'isabella','isabelle','isla','ivy',
  'jacqueline','jade','jamie','jan','jana','jane','janet','janice','janine','jasmine',
  'jean','jeanette','jeanne','jenna','jennifer','jenny','jessica','jill','jillian',
  'joan','joanna','jocelyn','jodi','jolene','jordan','josephine','joy','joyce','juanita',
  'judith','judy','julia','juliana','julie','juliet','june','justine',
  'kaitlyn','kara','karen','karina','karla','kate','katherine','kathleen','kathryn',
  'kathy','katie','katrina','kay','kayla','keiko','keira','kelly','kelsey','kendra',
  'kennedy','kerry','kimberly','kira','kristen','kristin','kristina','krystal','kylie',
  'lacey','laila','lana','lara','larissa','laura','lauren','laurie','layla','lea','leah',
  'leigh','lena','leona','leslie','leticia','lila','lillian','lily','linda','lindsay',
  'lisa','liz','logan','lois','lola','lorena','loretta','lori','lorraine','louise',
  'lucia','lucille','lucy','luna','lydia','lynn',
  'mabel','mackenzie','maddison','madeline','madison','mae','maggie','maisie','mallory',
  'mandy','marcella','marcia','margaret','margarita','maria','marian','marianne','marie',
  'marilyn','marina','marissa','marjorie','marlene','marsha','martha','mary','matilda',
  'maureen','maya','megan','melanie','melinda','melissa','melody','mercedes','meredith',
  'mia','michaela','michelle','mildred','millie','mindy','miranda','miriam','misty',
  'molly','monica','monique','morgan','muriel','mya','myra','myrtle',
  'nadia','nadine','nancy','naomi','natalie','natasha','nellie','neha','nicole','nina',
  'nisha','noel','nora','norma','nova',
  'octavia','olga','olive','olivia','opal','ophelia',
  'paige','pam','pamela','patricia','patsy','patti','patty','paula','pauline','pearl',
  'peggy','penelope','penny','petra','phyllis','piper','pooja','poppy','portia','priscilla',
  'priya',
  'queen',
  'rachael','rachel','ramona','raquel','raven','rebecca','regina','renee','rhea','rhonda',
  'riley','rita','roberta','robin','rochelle','rosa','rosalie','rose','rosemary','rosie',
  'roxanne','ruby','ruth',
  'sabrina','sadie','sally','samantha','sandra','sandy','sara','sarah','savannah',
  'scarlett','selena','serena','shannon','sharon','shauna','sheila','shelby','shelley',
  'sherry','shirley','sierra','silvia','simone','sonia','sophia','sophie','stacey',
  'stacy','stella','stephanie','sue','summer','susan','susanne','suzanne','sybil','sylvia',
  'tabitha','tamara','tammy','tanya','tara','tasha','tatiana','taylor','teresa','terri',
  'tess','tessa','thelma','theresa','tiffany','tina','toni','tonya','tracy','tricia',
  'trudy',
  'uma','ursula',
  'valentina','valerie','vanessa','vera','veronica','vicky','victoria','viola','violet',
  'virginia','vivian','vivienne',
  'wanda','wendy','whitney','willow','wilma','winifred',
  'ximena','xena',
  'yasmin','yolanda','yvette','yvonne',
  'zara','zelda','zoe','zoey',
]);

/**
 * Detect likely gender from a person's name.
 * Uses the first word of the name (first name) for matching.
 * @param {string} fullName
 * @returns {'male'|'female'|null}
 */
function detectGender(fullName) {
  if (!fullName || typeof fullName !== 'string') return null;
  const firstName = fullName.trim().split(/\s+/)[0].toLowerCase();
  if (!firstName) return null;
  if (MALE_NAMES.has(firstName)) return 'male';
  if (FEMALE_NAMES.has(firstName)) return 'female';
  return null;
}

module.exports = { detectGender };
